name: shju
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  
  line_icons: ^0.2.0
  provider: ^4.0.4
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/icons/facebook.png
     - assets/cover.png
     - assets/images/icons/google.png
     - assets/images/icons/linkedin.png
     - assets/images/nike.jpeg
     - assets/images/blue.jpeg
     - assets/images/casual.jpg
     - assets/images/ccc.jpg
     - assets/images/nike.jpeg
     - assets/images/converse.jpg
     - assets/images/cover1.jpg
     - assets/images/cover2.png
     - assets/images/pink.jpg
     - assets/images/sad.jpg
     - assets/images/sfefc.jpg
     - assets/images/sneak.jpeg
     - assets/images/superstar.jpg
     - assets/images/yellow.jpg
     - assets/images/loadcover.png
     - assets/images/categories/armyboots.jpg
     - assets/images/categories/casual.jpg
     - assets/images/categories/derby.jpg
     - assets/images/categories/flipflops.jpg
     - assets/images/categories/heal.jpg
     - assets/images/categories/loafers.jpeg
     - assets/images/categories/slipon.jpg
     - assets/images/categories/sneakers.jpeg
     - assets/images/categories/sports.jpeg
     - assets/images/footer/one.png
     - assets/images/footer/two.png
     - assets/images/footer/three.png
     - assets/images/footer/four.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Title
       fonts:
         - asset: assets/AndaleMono.ttf
         
     - family: Subtextregular
       fonts:
         - asset: assets/Balo_regular.ttf
          
     - family: Subtextbold 
       fonts:
         - asset: assets/Balo_SemiBold.ttf
           
     - family: Heading
       fonts:
         - asset: assets/Manrope-Bold.ttf
         - asset: assets/Manrope-Medium.ttf
         - asset: assets/Manrope-Regular.ttf
         - asset: assets/Manrope-SemiBold.ttf
           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
